# Generated by Django 3.1.7 on 2021-05-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taylors_book_club', '0004_auto_20210501_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='books',
            new_name='current_books',
        ),
    ]
