# Generated by Django 3.1.7 on 2021-05-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taylors_book_club', '0005_auto_20210501_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentbook',
            old_name='current_book',
            new_name='is_current_book',
        ),
    ]
