# Generated by Django 3.1.7 on 2021-05-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taylors_book_club', '0007_auto_20210501_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taylors_book_club.book')),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='current_books',
        ),
        migrations.DeleteModel(
            name='CurrentBook',
        ),
        migrations.AddField(
            model_name='club',
            name='current_book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CurrentBook', to='taylors_book_club.clubbook'),
        ),
        migrations.AddField(
            model_name='club',
            name='past_books',
            field=models.ManyToManyField(related_name='PastBooks', to='taylors_book_club.ClubBook'),
        ),
    ]
