GET http://localhost:3000/
Content-Type: application/json

### Register a user
POST http://localhost:3000/register
Content-Type:  application/json

{
    "email" : "noahskorner@gmail.com",
    "password1" : "Password123",
    "password2" : "Password123"
}

### Login a user
POST http://localhost:3000/login
Content-Type:  application/json

{
    "email" : "noahskorner@gmail.com",
    "password" : "Password123"
}

### Refresh a token
POST http://localhost:3000/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoibm9haHNrb3JuZXJAZ21haWwuY29tIiwiaWF0IjoxNjMxMjM5NDYyfQ.ti6looKUp6AjltBSBSPZpnxt1VQClSQYoQCANpUFycw"
}

### Logout user
DELETE http://localhost:3000/Logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoibm9haHNrb3JuZXJAZ21haWwuY29tIiwiaWF0IjoxNjMxOTI4MDk0fQ.D7K_7g-myprzDX4rCY_a9EQjlMI7ldhPFfSfNFEASoY"
}